<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test1"
           tests="4"
           failures="1"
           errors="0"
           skipped="2"
           time="0.019">
  <properties />
            <testcase name="f1" time="0.002" classname="com.xiaoyun.testcases.LoginTest1">
                <failure type="java.lang.AssertionError"
                  message="¶ÏÑÔÊ§°Ü"
              >
<![CDATA[java.lang.AssertionError: ¶ÏÑÔÊ§°Ü
  org.testng.Assert.fail(Assert.java:93)
  com.xiaoyun.utils.AssertUtil.checkIntNum(AssertUtil.java:13)
  com.xiaoyun.testcases.LoginTest1.f1(LoginTest1.java:22)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
      </failure>

          </testcase>
  
            <testcase name="f1" time="0.0" classname="com.xiaoyun.testcases.LoginTest1">
          <skipped />
    </testcase>
            <testcase name="f1" time="0.0" classname="com.xiaoyun.testcases.LoginTest1">
          <skipped />
    </testcase>
  
            <testcase name="f2" time="0.002" classname="com.xiaoyun.testcases.LoginTest1" />
      
</testsuite>
